### ISSUE TITLE
tree analyses

### ISSUE THREAD

**Issue by jensbast** [reubwn/hgt#4]
Sorry to bug you again...

Strangely, the script worked for 3 out of 4 taxa, but threw an error with this one:

 Rscript ./hgt/analyse_trees.R -p ./2_Sm_b1v03.mafft_alns/treefiles/ -o 2_Sm_b1v03.results.tab -f 2_Sm_b1v03.trees.pdf -q SM

Error in root.phylo(phy, outgroup = outgrp, resolve.root = TRUE) :
  specified outgroup not in labels of the tree
Calls: is.monophyletic -> root -> root.phylo
Execution halted

We also tried to manually set delimiter with "-d _" but did not change.
Do you know what this could be?
Something conflicting with headers maybe?

Best,
Jens

**Comment by reubwn** [comment]
Hmm, what does the treefile look like that's causing the error?

**Comment by jensbast** [comment]
we use a whole folder with the trees and can not make out the single tree that is causing the problem.
Nothing unusual as far as I can see in the tree files compared to the other species

**Comment by reubwn** [comment]
Since it is working on the other files, I agree it seems most likely there is something going on with the headers in that particular file(s) - the error basically says it cannot identify which taxon to use as the root: 
>specified outgroup not in labels of the tree

The program makes numerous calls to `is.monophyletic` so it's unclear which is causing the error (maybe all of them). One way of debugging the file would be just scrape the code into RStudio and go line-by-line to see where the error come up. Also check your case/typos, e.g. "SM" vs "Sm" etc.

PS, that's cool that you are finding a higher putative HGT in the asexual mites - these were not in the JoH paper?

**Comment by jensbast** [comment]
Cool, we will try this.

No, not in the JoH, because these are not published yet and were generated with WGA, so not nice for read-based analyses. And genomes are pretty fragmented (genes seem to be completely assembled though). So for HGT, we need mostly the support from introns and phylogenies. We did some a priori cleaning of scaffolds (i.e. removing the ones that had non-metazoan hits only according to blobtools). We have at the moment 2 sex-asex pairs of mites.

**Comment by reubwn** [comment]
Ah yes makes sense. 

I would be a bit careful of introns, I think it is not a great measure of the "metazoan-ness" of a gene - for example, if you take the genome of _E. coli_ and run some eukaryotic gene prediction on it (e.g. Augustus) then you get introns... i.e., if the gene prediction tool is looking for introns it will find them anyway. Also annotation errors may introduce problems in the gene models - I don't know about the mites but in the bdelloids there are loads of mis-annotations (missed exons, missed introns, merged genes, split genes, truncated genes...) - you don't see it at the genome level but when you go digging there are lots of issues (depressingly).

Linkage to a well-behaved metazoan gene is probably the best single measure, but that might be tricky if the N50 is low. Even the phylogenetic analysis is not perfect, as it cannot rule out gene loss from other lineages (as well as other issues). Blobtools is always a good idea!

Sounds like a really cool comparison a bit like the stick insects. Good luck!

**Comment by jensbast** [comment]
We annotated the mites using MAKER2 with transcriptomic training / evidence. Do you think it is saver to say that these annotations might be real introns?

**Comment by reubwn** [comment]
I suppose I meant in the case of sneaky bits of non-target DNA remaining in the assemblies, then being called as HGT. In the bdelloids, we removed all the obvious contamination using blobtools, but it might be possible for small fragments to remain if they are hiding underneath the bdelloid scaffolds (i.e. if they inhabit the same GC-coverage space). Then, they might be annotated (perhaps with introns) and be called as a HGT candidate. In this case, they should not be attached to any metazoan genes but would be on a scaffold that contained only HGT candidate genes - this would be a red flag for me, and the pipeline detects these cases automatically and throws them away. Probably your mites are much better assemblies and so the chance of this kind of thing is much smaller anyway!

On top of that, I think evidence of expression (e.g. the HGT candidate is also in the transcriptome) is also a good measure that the gene is really from the target organism, and is also expressed and so might be in the category of "functional" HGT rather than dead-on-arrival.

But I do think that most eukaryotic gene prediction programs would try to annotate an intron at any GT-AG sites it found, even in a bacterial genome!

**Comment by reubwn** [comment]
This is the analysis I was talking about, from the tardigrade guys: https://gist.github.com/GDKO/bc507bc9b620e6006a44

**Comment by jensbast** [comment]
hey, unfortunately, we could not identify the problem.
Would you be willing to double check if I send you the input trees and the command?

Another question: the numbers of entries in the Metazoan HGT candidates file (.HGT_candidates.Metazoa.hU30.CHS90.txt) are not the same as the overall summary (.HGT_locations.overall_summary.txt) would suggest. is there an additional filter or just these with >=30 for hU, >=90% for CHS in the metazoan file (.HGT_candidates.Metazoa.hU30.CHS90.txt)? Are these combined with intron evidence or so? (sorry if I mix something up) Or where are the intron candidates listed?
I asked because we want to combine all evidence: CHS, intron, phylogeny, (linkage), expression

**Comment by reubwn** [comment]
Hi Jens,

> Would you be willing to double check if I send you the input trees and the command?

Yes I'd be happy to take a look - cannot guarantee I will be super fast however, hopefully later this week.

The file "\***.HGT_candidates.Metazoa.hU30.CHS90.txt**" comes from the first script (`diamond_to_HGT_candidates.pl`) whereas the file "\***.HGT_locations.overall_summary.txt**" comes from the second script `get_locations_of_HGT_candidates.pl`, so yes there are different filters being applied. The first file gives any gene with hU and CHS over the thresholds (default = 30 and 90% respectively) and does not consider anything else, e.g. the linkage to an unambiguous ingroup gene or the presence of introns. Hope that makes sense? Basically the numbers reported in the second file you mention are subsets of the HGTc identified in the previous step. 

HGTc with introns are not printed explicitly to a separate file. For introns, view the file called "\***.HGT_locations.txt**" where the number of introns for all genes are given in the 7th column. To count the number of HGTc with introns (but discounting any other filters!) you can run something like:

```
> grep -Ff <(perl -lane 'print $F[3] if $F[6] > 0' *.HGT_locations.txt) *.HGT_candidates.Metazoa.hU30.CHS90.txt | wc -l
```

**Comment by jensbast** [comment]
Thanks for the explanation. Cool, that makes sense. It does what I thought :) was just confused by the intron thing. Thanks for the script for collecting these. We want to see how much and which we can get for all evidence overlapping.

About the trees: I will send the zipped tree folder to your email address via WeTransfer.
Command used was:
```
Rscript ./hgt/analyse_trees.R 
-p ./2_Sm_b1v03.mafft_alns/treefiles/ 
-o 2_Sm_b1v03.results.tab 
-f 2_Sm_b1v03.trees.pdf 
-q SM
```

**Comment by reubwn** [comment]
Hi Jens, 

I added a `--verbose` flag to the analyse_trees.R script that prints out the current tree that's being worked on, and this showed that it was treefile "SM_20723-RA.fasta.mafft.treefile" that was causing the rooting failure. Inspection of this tree revealed the problem: there were two (paraphyletic) taxa that contained the string "SM": **SM**_06457-RA and UniRef90_A0A1Y1X**SM**4_OUT_Eukaryota_Fungi_Zoopagomycota. Simple as that!

You can get around it here simply by running:
```
Rscript ./hgt/analyse_trees.R \
-p ./2_Sm_b1v03.mafft_alns/treefiles/ \
-o 2_Sm_b1v03.results.tab \
-f 2_Sm_b1v03.trees.pdf \
-q SM_
```

i.e. including the underscore in the `-q` identifying string parameter, which disambiguates the focal gene IDs from anything in the UniProt IDs. I tested it and it ran to completion so hopefully that will work for you.

Cheers,
R
