### ISSUE TITLE
taxid_skip ERROR

### ISSUE THREAD

**Issue by cfz1998** [reubwn/hgt#6]
Hi! @reubwn 
Happy New Year!

Does the `taxid_skip` can not skip itself?
The `.blast.taxid.gz.HGT_results.Dothideomycetes.txt` contains the taxid that I set skipped.

Thank you for your reply.

**Comment by cfz1998** [comment]
![image](https://github.com/reubwn/hgt/assets/60096719/530c13e1-c3d4-4236-b04b-f22e436cea97)

![image](https://github.com/reubwn/hgt/assets/60096719/a089cf44-0407-4c4a-8702-a6092bebc7e5)

**Comment by cfz1998** [comment]
My running code:
```shell
perl diamond_to_HGT_candidates.pl -i 01.res/${line}.blast.taxid.gz -f 00.data/${line}.pep -p /data/chaofan/source/02.taxid -k 5598 -t 147541 -s 80
```

**Comment by cfz1998** [comment]
![image](https://github.com/reubwn/hgt/assets/60096719/c6e7e0bf-466c-405e-b541-15db1f4f9120)

Maybe this works?

**Comment by reubwn** [comment]
Hi, sorry it took me so long to reply to this.

It might be because you are setting the taxid skip parameter (`-k 5598` = genus Alternaria) at quite a low taxonomic level (genus) - usually I would set it to be much higher up the tree (e.g. phylum), so my code might be breaking at this fine-scale level of analysis... let me look...

**Comment by reubwn** [comment]
Yes I think you are right, the problem is that the taxid for the protein in question (UniRef90_A0A177D7E1) is the same as the taxid set to be skipped, both = 5598.

```
>> zcat uniref90.fasta.gz | rg -F A0A177D7E1 
>UniRef90_A0A177D7E1 Peripla_BP_6 domain-containing protein n=7 Tax=Alternaria TaxID=5598 RepID=A0A177D7E1_ALTAL
```

So the first parent (5599) is already above the level set to be skipped, and so it is missed. Your code suggestion will work I think, if you want to do a pull request I can merge it (otherwise I will edit myself). 

Thanks for catching this!

**Comment by cfz1998** [comment]
@reubwn  Thank you!
I do not know how to `pull request`.  =.=

Thank you for fixing it.
